##############################################
#                                            #
#                Send module                 #
#           Response for operation           #
#           on send files to testers         #
#                                            #
##############################################
import os
import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

import requests

from utils import print_utils

from datetime import datetime
import bin.constants

def send_to_email(project_name, file_urls, global_time, local_path=None):
    if os.getenv('EMAIL_ENABLED', 'false').lower() != "true":
        return

    # Extract project key (e.g., "hurryApp" from "hurryApp [release]")
    project_key = project_name.split(' [')[0]
    build_type = project_name.split(' [')[1] if ' [' in project_name else ""
    
    # Get nice name for display
    nice_name = bin.constants.projects.get(project_key, project_key)
    display_title = f"{nice_name} {build_type}" if build_type else nice_name
    
    brand_color = bin.constants.project_colors.get(project_key, "#007bff")

    print(print_utils.success(f"[{display_title}] Sending professional email notification ..."))
    emails = os.getenv("EMAILS")
    if not emails: return
    
    emails = emails.split(',')
    sender_email = os.getenv("EMAIL_USER")
    sender_password = os.getenv("EMAIL_PASSWORD")
    smtp_host = os.getenv("SMTP_HOST")
    smtp_port = int(os.getenv("SMTP_PORT", 587))

    if not all([sender_email, sender_password, smtp_host]):
        return

    try:
        message = MIMEMultipart("alternative")
        message['From'] = f"APK Professional Builder <{sender_email}>"
        message['Subject'] = f"🚀 {display_title} - Build Report ({global_time})"

        # HTML Body
        links_html = "".join([
            f'<tr><td style="padding: 10px; border: 1px solid #ddd; font-weight: bold;">{k.upper()}</td>'
            f'<td style="padding: 10px; border: 1px solid #ddd;"><a href="{v}" style="color: {brand_color}; text-decoration: none;">Download</a></td></tr>' 
            for k, v in file_urls.items()
        ])
        
        local_path_html = ""
        if local_path:
            local_path_html = f"""
            <div style="margin-top: 20px; padding: 15px; background-color: #f8f9fa; border-left: 5px solid {brand_color};">
                <b style="color: #333;">📂 Local Folder Path:</b><br>
                <code style="display: block; margin-top: 5px; color: #d63384;">{local_path}</code>
            </div>
            """

        html = f"""
        <html>
        <body style="font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; line-height: 1.6; color: #333; max-width: 600px; margin: auto;">
            <div style="background: {brand_color}; color: white; padding: 30px; text-align: center; border-radius: 10px 10px 0 0;">
                <h1 style="margin: 0; font-size: 24px;">Build Success! 🚀</h1>
                <p style="margin: 5px 0 0; opacity: 0.9;">Project: {display_title}</p>
            </div>
            <div style="padding: 30px; border: 1px solid #eee; border-top: none; border-radius: 0 0 10px 10px; box-shadow: 0 4px 6px rgba(0,0,0,0.05);">
                <p>Hello Team,</p>
                <p>A new build of <b>{display_title}</b> has been completed successfully and is ready for testing.</p>
                
                <h3 style="color: {brand_color}; border-bottom: 2px solid #f0f0f0; padding-bottom: 5px;">📦 Build Details</h3>
                <table style="width: 100%; border-collapse: collapse; margin-top: 10px;">
                    {links_html}
                </table>

                {local_path_html}

                <div style="margin-top: 30px; padding-top: 20px; border-top: 1px solid #eee; font-size: 12px; color: #888; text-align: center;">
                    <p>Generated by APK Professional Builder System<br>Time: {global_time}</p>
                </div>
            </div>
        </body>
        </html>
        """
        message.attach(MIMEText(html, 'html'))

        with smtplib.SMTP(smtp_host, smtp_port) as server:
            server.starttls()
            server.login(sender_email, sender_password)
            for email in emails:
                message['To'] = email.strip()
                server.sendmail(sender_email, email.strip(), message.as_string())

        print(print_utils.warning(f"[{project_name}] Email sent successfully"))
    except Exception as e:
        print(print_utils.danger(f"[{project_name}] Email failed: {e}"))


def send_to_discord(project_name, file_urls, global_time, local_path=None):
    if os.getenv('DISCORD_ENABLED', 'false').lower() != "true":
        return

    # Extract project key
    project_key = project_name.split(' [')[0]
    build_type = project_name.split(' [')[1] if ' [' in project_name else ""
    
    # Get nice name for display
    nice_name = bin.constants.projects.get(project_key, project_key)
    display_title = f"{nice_name} {build_type}" if build_type else nice_name

    brand_color_hex = bin.constants.project_colors.get(project_key, "#007bff")
    # Convert hex to decimal for Discord
    brand_color_dec = int(brand_color_hex.lstrip('#'), 16)

    print(print_utils.success(f"[{display_title}] Sending Discord notification ..."))
    url = os.getenv("DISCORD_WEBHOOK")
    if not url: return

    try:
        fields = []
        for k, v in file_urls.items():
            fields.append({
                "name": f"📥 {k.upper()} Link",
                "value": f"[Click to Download]({v})",
                "inline": True
            })
        
        if local_path:
            fields.append({
                "name": "📂 Local Workspace Path",
                "value": f"```\n{local_path}\n```",
                "inline": False
            })

        embed = {
            "title": f"🚀 New Build: {display_title}",
            "color": brand_color_dec,
            "timestamp": datetime.now().isoformat(),
            "footer": {
                "text": "APK Professional Builder v2.0"
            },
            "fields": fields
        }

        requests.post(url, json={"embeds": [embed]})
        print(print_utils.warning(f"[{project_name}] Discord notification sent"))
    except Exception as e:
        print(print_utils.danger(f"[{project_name}] Discord failed: {e}"))



